"""create calls table

Revision ID: 22c515c2df76
Revises: 
Create Date: 2026-01-29 14:58:02.535152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22c515c2df76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'PROCESSING_AI', 'COMPLETED', 'FAILED', 'ARCHIVED', name='callstatus'), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.Column('packet_count', sa.Integer(), nullable=False),
    sa.Column('transcription', sa.String(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_index(op.f('ix_calls_call_id'), 'calls', ['call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calls_call_id'), table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
